DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS ORDER_DETAILS;

CREATE TABLE USERS (
  ID SERIAL PRIMARY KEY NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  ADDRESS VARCHAR(255),
  ZIPCODE VARCHAR(255),
  PROVINCE VARCHAR(255),
  COUNTRY VARCHAR(255)
);

CREATE TABLE PRODUCTS (
   ID SERIAL PRIMARY KEY NOT NULL,
   ITEM_NAME VARCHAR(255) NOT NULL,
   DESCRIPTION TEXT,
   PRICE_CENTS INTEGER NOT NULL DEFAULT 0,
   PHOTO_URL VARCHAR(255) NOT NULL,
   KEYWORDS TEXT,
   CATEGORY_ID INTEGER REFERENCES category(id) ON DELETE CASCADE
)

CREATE TABLE ORDERS (
  ID SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  shipping_name VARCHAR(255) NOT NULL,
  shipping_address VARCHAR(255) NOT NULL,
  shipping_email VARCHAR(255) NOT NULL,
  shipping_zipcode VARCHAR(255) NOT NULL,
  shipping_province VARCHAR(255) NOT NULL,
  shipping_country VARCHAR(255) NOT NULL,
  total_cents INTEGER NOT NULL DEFAULT 0,
  payment VARCHAR(255) NOT NULL
)

CREATE TABLE ORDER_DETAILS (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES product(id) ON DELETE CASCADE,
  price_cents INTEGER NOT NULL DEFAULT 0,
  quantity INTEGER NOT NULL DEFAULT 0
)

CREATE TABLE CATEGORIES (
  id SERIAL PRIMARY KEY NOT NULL,
  category_name VARCHAR(255) NOT NULL
)