DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS ORDER_DETAILS;

CREATE TABLE USERS (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  address VARCHAR(255),
  zipcode VARCHAR(255),
  province VARCHAR(255),
  country VARCHAR(255)
);

CREATE TABLE PRODUCTS (
   id SERIAL PRIMARY KEY NOT NULL,
   item_name VARCHAR(255) NOT NULL,
   description TEXT,
   price_cents INTEGER NOT NULL DEFAULT 0,
   photo_url VARCHAR(255) NOT NULL,
   keywords TEXT,
   category INTEGER REFERENCES categories(id) ON DELETE CASCADE
)

CREATE TABLE ORDERS (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  shipping_name VARCHAR(255) NOT NULL,
  shipping_address VARCHAR(255) NOT NULL,
  shipping_email VARCHAR(255) NOT NULL,
  shipping_zipcode VARCHAR(255) NOT NULL,
  shipping_province VARCHAR(255) NOT NULL,
  shipping_country VARCHAR(255) NOT NULL,
  total_cents INTEGER NOT NULL DEFAULT 0,
  payment VARCHAR(255) NOT NULL
)

CREATE TABLE ORDER_DETAILS (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  price_cents INTEGER NOT NULL DEFAULT 0,
  quantity INTEGER NOT NULL DEFAULT 0
)

CREATE TABLE CATEGORIES (
  id SERIAL PRIMARY KEY NOT NULL,
  category_name VARCHAR(255) NOT NULL
)